env:
  es2017: true
  browser: true
  commonjs: true

extends: ['airbnb-typescript']
include: ["src/**/*.tsx"]
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    tsx: true
  ecmaVersion: 2018
  sourceType: module

plugins: ['react', '@typescript-eslint']

settings:
  react:
    version: '16'

